name: "godot-ci export"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: Kenney-Jam-2021

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $EXPORT_NAME
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          cd $EXPORT_NAME
          godot -v --export "Mac OSX" ../build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: build/mac

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $EXPORT_NAME
          godot -v --export "HTML5" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web

  deploy-itch-win:
    name: Windows Itch.io Deploy
    runs-on: ubuntu-latest
    needs: export-windows
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Prepare Directory
        run: |
          mkdir -v -p deploy/win
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: windows
          # Destination path
          path: ./deploy/win/windows.zip
      - name: Butler
        env: # Or as an environment variable
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
        run: |
          butler push ./deploy/win/windows.zip $ITCHIO_USERNAME/$ITCHIO_GAME:windows

  deploy-itch-mac:
    name: Mac Itch.io Deploy
    runs-on: ubuntu-latest
    needs: export-mac
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Prepare Directory
        run: |
          mkdir -v -p deploy/mac
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: mac
          # Destination path
          path: ./deploy/mac/mac.zip
      - name: Butler
        env: # Or as an environment variable
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
        run: |
          butler push ./deploy/mac/mac.zip $ITCHIO_USERNAME/$ITCHIO_GAME:mac

  deploy-itch-linux:
    name: Linux Itch.io Deploy
    runs-on: ubuntu-latest
    needs: export-linux
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Prepare Directory
        run: |
          mkdir -v -p deploy/linux
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: linux
          # Destination path
          path: ./deploy/linux/linux.zip
      - name: Butler
        env: # Or as an environment variable
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
        run: |
          butler push ./deploy/linux/linux.zip $ITCHIO_USERNAME/$ITCHIO_GAME:linux

  deploy-itch-web:
    name: Web Itch.io Deploy
    runs-on: ubuntu-latest
    needs: export-web
    container:
      image: barichello/godot-ci:3.2.3
    steps:
      - name: Prepare Directory
        run: |
          mkdir -v -p deploy/web
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: web
          # Destination path
          path: ./deploy/web/web.zip
      - name: Butler
        env: # Or as an environment variable
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
        run: |
          butler push ./deploy/web/web.zip $ITCHIO_USERNAME/$ITCHIO_GAME:web